### PR TITLE
Add .svelte files support

### PR DESCRIPTION
**Pull request by MNouriWork**
I add .svelte projects support and fixed it

### CODE REVIEW

**Comment by emranweb** [comment]
@MNouriWork Thanks for your work. I will check and update you soon.

**Comment by MNouriWork** [comment]
You're welcome. It was my pleasure 😊

**Comment by emranweb** [comment]
The new version was released, v1.0.2, with svelte support. @MNouriWork Please check

**Comment by MNouriWork** [comment]
Yes, I checked. Thank you for your work👍

**Pull request merged**
